version: "3.1"

services:
  api:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    - www-html:/var/www/html
    - etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - api
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email almas.zhumakhanov.2002a@gmail.com  --agree-tos --no-eff-email -d loom.kz

volumes:
  pgdata:
  www-html:
  etc-letsencrypt:
